# Generated by Django 2.1 on 2018-08-26 09:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_auto_20180824_2309'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 8, 26, 14, 45, 36, 401697)),
        ),
    ]
