# Generated by Django 2.1 on 2018-08-26 09:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_auto_20180826_1445'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 8, 26, 14, 49, 59, 210690)),
        ),
    ]
